### ISSUE TITLE
How to skip tests? 

### ISSUE THREAD

**Issue by clehene** [nicodewet/dotnet-maven-plugin#1]
`-DskipTests` doesn't work

**Comment by nicodewet** [comment]
Thanks for the feedback. Are you using this plugin? 

Happy to attend to it if you are.

**Comment by clehene** [comment]
Hey, thank you. I figured it out eventually.
I had a single pom for two csproj files. I eventually broken it down to two and one of them `dotnet-test`. That also solved an issue with nupkg push on the tests.
